// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmrpxcsjkcekilrslqlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcnB4Y3Nqa2Nla2lscnNscWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1ODgyODIsImV4cCI6MjA0OTE2NDI4Mn0.az-0D00W0AJBYZc5CxE_VaLjFBfRQJPGZ1xDyMXULuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);